spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*.xml
  type-aliases-package: com.gupao.mybatis.entity